#!/usr/bin/env python3
"""Regenerate GTOS Sans 14/28 from DejaVu Sans 2.37 using Pillow.
Normal builds use checked-in pixels; see docs/desktop-font-license.txt.
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
import argparse
p = argparse.ArgumentParser()
p.add_argument('--font', default='/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf')
p.add_argument('--output', default=str(Path(__file__).resolve().parents[1] / 'src/gui/modern_font_data.inc'))
a = p.parse_args()
lines = ['#include <common/types.h>',
         '// GTOS Sans 14/28: rasterized DejaVu Sans; see docs/desktop-font-license.txt.',
         '// Generated by tests/desktop_font.py. Two 4-bit coverage samples per byte.']
for scale, suffix in [(1, ''), (2, 'Large')]:
    f = ImageFont.truetype(a.font, 14 * scale)
    lines += [f'static const uint8_t modernFontAdvance{suffix}[95] = {{',
              ','.join(str(round(f.getlength(chr(c)))) for c in range(32, 127)) + '};',
              f'static const uint8_t modernFontPixels{suffix}[95][{144*scale*scale}] = {{']
    for c in range(32, 127):
        im = Image.new('L', (16 * scale, 18 * scale))
        ImageDraw.Draw(im).text((0, -2 * scale), chr(c), font=f, fill=255, anchor='la')
        data = list(im.tobytes())
        packed = [((data[n] + 8) // 17 << 4) | ((data[n + 1] + 8) // 17)
                  for n in range(0, len(data), 2)]
        lines.append('{' + ','.join(map(str, packed)) + '}, // ' + str(c))
    lines.append('};')
Path(a.output).write_text('\n'.join(lines) + '\n')
