#!/usr/bin/env python3
"""Reproduce the public PNG resource and independent source-pixel oracles."""
import argparse
import hashlib
import json
import pathlib
import struct
import zlib

def sha(data):
    return hashlib.sha256(data).hexdigest()

def literals(data):
    return ''.join('    '+','.join('0x%02x'%x for x in data[n:n+16])+',\n'
                   for n in range(0,len(data),16))

def generate(root,check):
    app=root/'apps/png_resource_probe'
    # A small colorful application icon, including hidden RGB, partial alpha,
    # and opaque pixels. The explicit pixel file is the oracle's source of truth.
    pixels=[]
    for y in range(16):
        for x in range(16):
            alpha=(0,64,128,192,255)[(x//3+y//3)%5]
            pixels.append([(17*x+11*y+23)%256,(7*x+19*y+41)%256,
                           (29*x+3*y+67)%256,alpha])
    source=dict(width=16,height=16,format='straight RGBA8',pixels=pixels)
    source_bytes=(json.dumps(source,indent=2)+'\n').encode()
    rgba=bytes(v for pixel in pixels for v in pixel)
    raw=b''.join(b'\0'+rgba[y*64:(y+1)*64] for y in range(16))
    # Exact one-block stored DEFLATE; no library compressor selection is involved.
    payload=b'\x78\x01\x01'+struct.pack('<HH',len(raw),len(raw)^0xffff)+raw
    payload+=struct.pack('>I',zlib.adler32(raw)&0xffffffff)
    def chunk(kind,data):
        return struct.pack('>I',len(data))+kind+data+struct.pack('>I',zlib.crc32(kind+data)&0xffffffff)
    png=b'\x89PNG\r\n\x1a\n'+chunk(b'IHDR',struct.pack('>IIBBBBB',16,16,8,6,0,0,0))
    png+=chunk(b'IDAT',payload)+chunk(b'IEND',b'')
    assert len(png)==1108 and zlib.decompress(payload)==raw
    bgra=bytes(v for r,g,b,a in pixels for v in (b,g,r,a))
    # Mathematical nearest-integer oracle, independently expressed from Skia.
    premul=bytes(v for r,g,b,a in pixels for v in
                 ((r*a+127)//255,(g*a+127)//255,(b*a+127)//255,a))
    header='''// Generated by tools/generate-native-png-resource.py; contains no PNG input.
#ifndef GTOS_PNG_RESOURCE_ORACLES_H
#define GTOS_PNG_RESOURCE_ORACLES_H
#include <stdint.h>
static const unsigned RESOURCE_PNG_BYTES=1108;
static const unsigned RESOURCE_WIDTH=16,RESOURCE_HEIGHT=16;
static const uint32_t RESOURCE_PNG_CRC32=0x%08xU;
static const uint8_t resource_expected_bgra[1024]={
%s};
static const uint8_t resource_expected_premul_rgba[1024]={
%s};
#endif
'''%(zlib.crc32(png)&0xffffffff,literals(bgra),literals(premul))
    inc=literals(png)
    manifest=dict(schema_version=1,resource_version=1,resource_id=1,
        type='static PNG',flags=['readonly','public'],png_bytes=len(png),
        width=16,height=16,bit_depth=8,color_type=6,interlace=0,
        compression='one stored DEFLATE block; 16 filter-zero scanlines',
        png_sha256=sha(png),png_crc32='%08x'%(zlib.crc32(png)&0xffffffff),
        source_pixels_sha256=sha(source_bytes),straight_rgba_sha256=sha(rgba),
        bgra_sha256=sha(bgra),premul_rgba_sha256=sha(premul),
        oracle_header_sha256=sha(header.encode()),kernel_include_sha256=sha(inc.encode()),
        oracle_method='Source pixels -> BGRA permutation; nearest(channel*alpha/255) by (channel*alpha+127)//255',
        trust='Fixed compiled kernel rodata catalog; manifest hashes are reproducibility evidence, not authentication',
        origin='New deterministic GTOS application resource; no external image or existing PNG fixture reused')
    outputs={app/'source_pixels.json':source_bytes,app/'resource.png':png,
             app/'resource_oracles.h':header.encode(),
             app/'resource_manifest.json':(json.dumps(manifest,indent=2)+'\n').encode(),
             root/'src/process/resources_png.inc':inc.encode()}
    for path,data in outputs.items():
        if check:
            assert path.read_bytes()==data,'Generated resource differs: '+str(path)
        else:
            path.parent.mkdir(parents=True,exist_ok=True)
            path.write_bytes(data)
    print(json.dumps(dict(check=check,png_bytes=len(png),png_sha256=sha(png),
                         independent_oracles=True),indent=2))

if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root',type=pathlib.Path,default=pathlib.Path(__file__).resolve().parents[1])
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    generate(args.root.resolve(),args.check)
