#!/usr/bin/env python3
"""Generate UTF-8 catalogs/dictionary and optionally the licensed GTOS Han atlas.
Normal kernel builds use generated files and need no Python/font packages.
"""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FONT_SHA256 = 'b76b0433203017ca80401b2ee0dd69350349871c4b19d504c34dbdd80541690a'

def inputs():
    catalog = json.loads((ROOT / 'tools/i18n_catalog.json').read_text())
    dictionary = json.loads((ROOT / 'tools/i18n_pinyin.json').read_text())
    ids = set()
    for row in catalog:
        assert row['id'].isascii() and row['id'].isidentifier() and row['id'] not in ids
        ids.add(row['id'])
        for locale in ('en', 'zh-CN'):
            assert row[locale] and '\0' not in row[locale]
    for spelling, candidates in dictionary.items():
        assert spelling.isascii() and spelling.isalpha() and spelling.islower()
        assert 1 <= len(spelling) <= 31 and 1 <= len(candidates) <= 9
        assert len(set(candidates)) == len(candidates)
        for phrase in candidates:
            assert phrase and len(phrase.encode()) < 64 and '\0' not in phrase
    return catalog, dictionary

def emit(path, content, check):
    if check:
        if not path.exists() or path.read_text() != content:
            raise SystemExit(f'Generated file differs: {path.relative_to(ROOT)}')
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)

def literal(value):
    return json.dumps(value, ensure_ascii=False)

def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--font', help='Regenerate font atlas from official NotoSansCJK-Regular.ttc')
    p.add_argument('--check', action='store_true')
    a = p.parse_args()
    catalog, dictionary = inputs()
    emit(ROOT / 'include/i18n/catalog_data.inc', '// Generated by tools/i18n_generate.py; edit tools/i18n_catalog.json.\n' + ''.join(
        f'GTOS_STRING({row["id"]}, {literal(row["en"])}, {literal(row["zh-CN"])})\n' for row in catalog), a.check)
    emit(ROOT / 'include/i18n/pinyin_data.inc', '// Generated by tools/i18n_generate.py; edit tools/i18n_pinyin.json.\n' + ''.join(
        '{' + literal(key) + ',' + str(len(candidates)) + ',{' + ','.join(map(literal, candidates)) + '}},\n'
        for key, candidates in sorted(dictionary.items())), a.check)
    if not a.font:
        if a.check:
            atlas_path = ROOT / 'include/i18n/han_font_data.inc'
            manifest = json.loads((ROOT / 'apps/fonts/han_manifest.json').read_text())
            required = {ord(c) for row in catalog for locale in ('en', 'zh-CN')
                        for c in row[locale] if ord(c) > 126}
            required |= {ord(c) for candidates in dictionary.values()
                         for phrase in candidates for c in phrase if ord(c) > 126}
            required.add(0x25A1)
            assert manifest['codepoints'] == [f'U+{p:04X}' for p in sorted(required)], 'Regenerate atlas coverage'
            assert manifest['glyph_count'] == len(required)
            assert manifest['atlas_binary_bytes'] == len(required) * 726
            assert manifest['atlas_source_sha256'] == hashlib.sha256(atlas_path.read_bytes()).hexdigest(), 'Atlas hash mismatch'
        return
    from PIL import Image, ImageDraw, ImageFont, features
    import PIL
    from fontTools.ttLib import TTCollection
    fontpath = Path(a.font)
    source_sha = hashlib.sha256(fontpath.read_bytes()).hexdigest()
    if source_sha != FONT_SHA256:
        raise SystemExit('Font SHA-256 mismatch; use the documented official Sans2.004 TTC')
    collection = TTCollection(fontpath)
    source = collection.fonts[2]
    assert source['name'].getDebugName(1) == 'Noto Sans CJK SC'
    cmap = source.getBestCmap()
    strings = [r[l] for r in catalog for l in ('en', 'zh-CN')]
    strings += [s for row in dictionary.values() for s in row]
    points = sorted({ord(c) for s in strings for c in s if ord(c) > 126} | {0x25A1})
    assert all(p in cmap and cmap[p] != '.notdef' for p in points), 'Uncovered glyph'
    lines = ['// Generated by tools/i18n_generate.py. GTOS Han, SIL OFL-1.1.',
             '// Complete license: apps/fonts/OFL.txt; source: apps/fonts/README.md.',
             'static const uint32_t hanCodepoints[] = {' + ','.join(hex(p) for p in points) + '};']
    for scale in (1, 2):
        font = ImageFont.truetype(str(fontpath), 14 * scale, index=2, layout_engine=ImageFont.Layout.BASIC)
        advance = [round(font.getlength(chr(p))) for p in points]
        lines += [f'static const uint8_t hanAdvance{scale}[] = {{' + ','.join(map(str,advance)) + '};',
                  f'static const uint8_t hanPixels{scale}[][ {144 * scale * scale} ] = {{']
        for point in points:
            im = Image.new('L', (16 * scale, 18 * scale))
            # Bounding-box verification prevents silently cropping source glyphs.
            box = font.getbbox(chr(point), anchor='la')
            assert box[0] >= 0 and box[2] <= im.width and box[1] - 3 * scale >= 0 and box[3] - 3 * scale <= im.height, (hex(point),box)
            ImageDraw.Draw(im).text((0, -3 * scale), chr(point), font=font, fill=255, anchor='la')
            data = list(im.tobytes())
            assert any(data), f'Empty rendered glyph U+{point:04X}'
            packed = [((data[i]+8)//17 << 4) | ((data[i+1]+8)//17) for i in range(0,len(data),2)]
            lines += ['{' + ','.join(map(str,packed)) + '}, // U+' + f'{point:04X}']
        lines += ['};']
    atlas = '\n'.join(lines) + '\n'
    emit(ROOT / 'include/i18n/han_font_data.inc', atlas, a.check)
    manifest = {'font': 'GTOS Han', 'source': 'Noto Sans CJK SC Regular 2.004', 'source_sha256':source_sha,
                'face_index':2,'pillow':PIL.__version__, 'freetype':features.version('freetype2'),
                'fonttools': __import__('fontTools').__version__, 'glyph_count':len(points),
                'atlas_binary_bytes':len(points)*(144+576+4+2),
                'atlas_source_sha256':hashlib.sha256(atlas.encode()).hexdigest(),
                'codepoints':[f'U+{p:04X}' for p in points]}
    # Version metadata is intentionally part of reproducibility checks.
    emit(ROOT / 'apps/fonts/han_manifest.json', json.dumps(manifest,indent=2)+'\n',a.check)
    print(f'{len(points)} glyphs; {manifest["atlas_binary_bytes"]} atlas bytes; all input glyphs verified')

if __name__ == '__main__':
    main()
